#!/bin/sh
# Build IsGPTNerfed.app (menu bar app) with SwiftPM and assemble an ad-hoc signed bundle.
# Usage: ./macos/build.sh [--run | --install | --zip]     (needs Xcode 26+ / macOS 26 SDK)
#   --run      launch from the build folder
#   --install  copy to ~/Applications and launch
#   --zip      write dist/IsGPTNerfed-<version>.zip for a GitHub release (ad-hoc signed: first launch needs
#              right-click → Open, or `xattr -dr com.apple.quarantine ~/Applications/IsGPTNerfed.app`)
set -eu
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
swift build -c release 2>&1 | grep -v '^\[' || true
BIN="$(swift build -c release --show-bin-path)/IsGPTNerfed"
[ -x "$BIN" ] || { echo "build failed: $BIN missing" >&2; exit 1; }
APP="$HERE/build/IsGPTNerfed.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/IsGPTNerfed"
cp "$HERE/Info.plist" "$APP/Contents/Info.plist"
# icon: macos/icon.png (1024x1024, e.g. generated by Codex imagegen) wins; otherwise macos/icon.svg is
# rasterised with Quick Look, which every Mac has. Alternatives live in macos/icons/.
rm -f "$HERE/build/icon.svg.png" "$HERE/build/icon_1024.png"
if [ -f "$HERE/icon.png" ]; then
  sips -z 1024 1024 "$HERE/icon.png" --out "$HERE/build/icon_1024.png" >/dev/null
else
  qlmanage -t -s 1024 -o "$HERE/build" "$HERE/icon.svg" >/dev/null 2>&1
  mv "$HERE/build/icon.svg.png" "$HERE/build/icon_1024.png"
fi
ICONSET="$HERE/build/AppIcon.iconset"
rm -rf "$ICONSET"; mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
  sips -z $s $s "$HERE/build/icon_1024.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
  d=$((s*2)); sips -z $d $d "$HERE/build/icon_1024.png" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
# bundle the plugin as a local marketplace so the app can install itself into Codex (panel → Install)
MK="$APP/Contents/Resources/marketplace"
mkdir -p "$MK/.agents/plugins"
cp -R "$HERE/../plugin" "$MK/plugin"
cp "$HERE/../.agents/plugins/marketplace.json" "$MK/.agents/plugins/marketplace.json"
find "$MK" -name '__pycache__' -type d -prune -exec rm -rf {} +
chmod +x "$MK/plugin/skills/is-gpt-nerfed/scripts/nerfed"
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || true
echo "built $APP"
case "${1:-}" in
  --run)
    pkill -x IsGPTNerfed 2>/dev/null || true
    open "$APP"
    echo "launched (menu bar)" ;;
  --install)
    DEST="$HOME/Applications/IsGPTNerfed.app"
    mkdir -p "$HOME/Applications"
    pkill -x IsGPTNerfed 2>/dev/null || true
    rm -rf "$DEST" && cp -R "$APP" "$DEST"
    open "$DEST"
    echo "installed to $DEST and launched (menu bar); enable 'Launch at login' in the panel's settings" ;;
  --zip)
    VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$HERE/Info.plist")"
    DIST="$HERE/../dist"; mkdir -p "$DIST"
    ZIP="$DIST/IsGPTNerfed-$VERSION.zip"; rm -f "$ZIP"
    ditto -c -k --keepParent "$APP" "$ZIP"
    shasum -a 256 "$ZIP" | tee "$ZIP.sha256"
    echo "release archive: $ZIP" ;;
esac
